# Generated by Django 5.2.4 on 2025-08-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
    ]
